program __EPSILON__
__CHAIN__ program := program file

__WRAP__ qualified-identifier := IDENTIFIER
__CHAIN__ qualified-identifier := qualified-identifier . IDENTIFIER

file := module-declaration imports statements

constructor-declaration := constructor parameter-list block-statement
