// Modules and imports

module-declaration := module qualified-identifier ;

imports __EPSILON__
__CHAIN__ imports := imports import

import := using import-clause ;

import-clause := module-import-clause
import-clause := wildcard-import-clause
import-clause := specific-import-clause

module-import-clause := qualified-identifier
wildcard-import-clause := * from qualified-identifier
specific-import-clause := { import-list } from qualified-identifier

__WRAP__ import-list := specific-import
__CHAIN__ import-list := import-list , specific-import

specific-import := IDENTIFIER
specific-import := aliased-specific-import