type := non-void-type
type := void

__WRAP__ raw-type := IDENTIFIER
__WRAP__ raw-type := builtin-type
template-params := !( template-param-list )
template-params := ! type

template-param-list := type
__CHAIN__ template-param-list := template-param-list , type

non-void-type := raw-type
non-void-type := raw-type template-params

unique-ptr := non-void-type *
shared-ptr := non-void-type &
reference := non-void-type &
nullable-unique-ptr := non-void-type * ?
nullable-shared-ptr := non-void-type $ ?
nullable-reference := non-void-type & ?
mutable-type := non-void-type mut

non-void-type := unique-ptr
non-void-type := shared-ptr
non-void-type := reference
non-void-type := nullable-unique-ptr
non-void-type := nullable-shared-ptr
non-void-type := nullable-reference

non-void-type := mutable-type