program

program __EPSILON__
__CHAIN__ program := program statement

statement := label-declaration
statement := constant
statement := text

// Label declaration

label-declaration := label-name :

// Type Definitions

location := register
location := @ register

constant := iconst
constant := fconst
constant := label-name
constant := cconst
constant := hconst

// Operators

op3 := add
op3 := fadd
op3 := sub
op3 := fsub
op3 := mul
op3 := fmul
op3 := div
op3 := fdiv
op3 := mod
op3 := fmod
op3 := or
op3 := and
op3 := xor
op3 := shl
op3 := shr

op2 := neg
op2 := fneg
op2 := not
op2 := new
op2 := del

dsp := dspc
dsp := dspi
dsp := dspf
inp := inpc
inp := inpi
inp := inpf

op1 := inc
op1 := dec

expr-inp := location <- inp jump-clause
expr-dsp := dsp <- location jump-clause
expr-1 := op1 location jump-clause
expr-2 := location <- op2 location jump-clause
expr-3 := location <- location op3 location jump-clause
expr-mov := location <- location jump-clause

jump-clause __EPSILON__
jump-clause := jmp cond
cond __EPSILON__
cond := <0
cond := <=0
cond := >0
cond := >=0
cond := !=0
cond := ==0

expr-lod := location <- constant

expr := expr-inp
expr := expr-dsp
expr := expr-1
expr := expr-2
expr := expr-3
expr := expr-mov
expr := expr-lod

statement := expr ;

statement := jump-clause ;